version: 2.1

jobs:
  build:
    environment:
      MINIO_STORAGE: https://storage.offen.dev
    docker:
      - image: circleci/ruby:2.7
    working_directory: ~/deb
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Download and import signing key
          command: |
            AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY aws --endpoint $MINIO_STORAGE s3 cp s3://secrets/signing-key.asc /tmp
            gpg --import /tmp/signing-key.asc
      - run:
          name: Install fpm and dpkg-sig
          command: |
            gem install --no-document fpm
            sudo apt-get install dpkg-sig
      - run:
          name: Package deb
          command: ./package.sh
      - run:
          name: Upload to S3
          command: |
            AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY aws --endpoint $MINIO_STORAGE s3 cp *.deb s3://deb/
            AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY aws --endpoint $MINIO_STORAGE s3 cp $(ls *.deb | head -n 1) s3://deb/offen_latest_amd64.deb

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: AWS
          filters:
            branches:
              only:
                - master

orbs:
  aws-cli: circleci/aws-cli@1.0.0
